unapp/Unapp-Ror/config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}
  root 'home#index'
  get 'home/index', to: 'home#index'

  get 'pages/about'

  get 'pages/blog'

  get 'pages/contact'

  get 'pages/services'

  get 'pages/work'

  get 'pages/work-grid'

  get 'pages/work-grid-without-text'

  get 'pages/test'

  resources :posts do
    collection do
      get :myposts
    end

    member do
      get :add_like
      get :delete_like
    end
  end
end

unapp/Unapp-Ror/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

unapp/Unapp-Ror/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

unapp/Unapp-Ror/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

unapp/Unapp-Ror/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes, dependent: :nullify
  mount_uploader :avatar, AvatarUploader
end

unapp/Unapp-Ror/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :nullify
  has_many :likes, dependent: :nullify
end

unapp/Unapp-Ror/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

unapp/Unapp-Ror/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

unapp/Unapp-Ror/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def blog
  end

  def contact
  end

  def services
  end

  def work
  end

  def work_grid
  end

  def work_grid_without_text
  end
end

unapp/Unapp-Ror/app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!, except: :index

  def index
    @post = Post.all()
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    @post.update(user_id:current_user.id)
    redirect_to(post_path(@post))
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to(post_path(@post))
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def add_like
    @post = Post.find(params[:id])
    if !(@post.likes.where(user_id: current_user.id).present?)
      @post.likes.create(user_id: current_user.id)
    end
  @liked = @post.likes.where(user: current_user).present?
  end

  def delete_like
    @post = Post.find(params[:id])
    @post.likes.where({user_id: current_user.id}).first.destroy
    @liked = @post.likes.where(user: current_user).present?
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :avatar)
  end

end

unapp/Unapp-Ror/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

unapp/Unapp-Ror/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

unapp/Unapp-Ror/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

unapp/Unapp-Ror/app/helpers/application_helper.rb
module ApplicationHelper
end

unapp/Unapp-Ror/app/helpers/home_helper.rb
module HomeHelper
end

unapp/Unapp-Ror/app/helpers/pages_helper.rb
module PagesHelper
end

unapp/Unapp-Ror/app/helpers/posts_helper.rb
module PostsHelper
end

unapp/Unapp-Ror/app/views/home/index.html.erb
<section id="home" class="video-hero bg-main-1" data-section="home">
	<div class="overlay"></div>
	<a class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=vqqt5p0q-eU',containment:'#home', showControls:false, autoPlay:true, loop:true, mute:true, startAt:0, opacity:1, quality:'default'}"></a>
	<div class="display-t text-center">
		<div class="display-tc">
			<div class="container">
				<div class="col-md-12 col-md-offset-0">
					<div class="animate-box">
						<h2>Take on your biggest projects and goals</h2>
						<p>with Unapp's high quality features</p>
						<p>
							<a href="gallery.html" class="btn btn-primary btn-lg btn-custom">Get premium</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<div class="colorlib-featured">
	<div class="row animate-box">
		<div class="featured-wrap">
			<div class="owl-carousel">
				<div class="item">
					<div class="col-md-8 col-md-offset-2">
						<div class="featured-entry">
							<%=image_tag("dashboard_full_1.jpg",class:"img-responsive", alt: "")%>

						</div>
					</div>
				</div>
				<div class="item">
					<div class="col-md-8 col-md-offset-2">
						<div class="featured-entry">
							<%=image_tag("dashboard_full_2.jpg",class:"img-responsive", alt: "")%>

						</div>
					</div>
				</div>
				<div class="item">
					<div class="col-md-8 col-md-offset-2">
						<div class="featured-entry">
							<%=image_tag("dashboard_full_3.jpg",class:"img-responsive", alt: "")%>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="colorlib-services colorlib-bg-white">
	<div class="container">
		<div class="row">
			<div class="col-md-4 text-center animate-box">
				<div class="services">
					<span class="icon">
						<i class="icon-browser"></i>
					</span>
					<div class="desc">
						<h3>Create your own template</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div>
				</div>
			</div>
			<div class="col-md-4 text-center animate-box">
				<div class="services">
					<span class="icon">
						<i class="icon-download"></i>
					</span>
					<div class="desc">
						<h3>Automatic Backup Data</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div>
				</div>
			</div>
			<div class="col-md-4 text-center animate-box">
				<div class="services">
					<span class="icon">
						<i class="icon-layers"></i>
					</span>
					<div class="desc">
						<h3>Page Builder</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="colorlib-intro">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
				<h2>Collaborate with your design team in a new way</h2>
				<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
					a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 animate-box">
				<span class="play">
					<a href="https://vimeo.com/channels/staffpicks/93951774" class="pulse popup-vimeo">
						<i class="icon-play3"></i>
					</a>
				</span>
			</div>
		</div>
	</div>
</div>

<div class="colorlib-work-featured colorlib-bg-white">
	<div class="container">
		<div class="row mobile-wrap">
			<div class="col-md-5 animate-box">
				<%=image_tag("mobile-2.jpg",class:"mobile-img", alt: "")%>

			</div>
			<div class="col-md-7 animate-box">
				<div class="desc">
					<h2>Real template creation</h2>
					<div class="features">
						<span class="icon">
							<i class="icon-lightbulb"></i>
						</span>
						<div class="f-desc">
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
								a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
						</div>
					</div>
					<div class="features">
						<span class="icon">
							<i class="icon-circle-compass"></i>
						</span>
						<div class="f-desc">
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
								a small line of blind text by the name</p>
						</div>
					</div>
					<div class="features">
						<span class="icon">
							<i class="icon-beaker"></i>
						</span>
						<div class="f-desc">
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
								a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
						</div>
					</div>
					<p>
						<a href="#" class="btn btn-primary btn-outline with-arrow">Start collaborating
							<i class="icon-arrow-right3"></i>
						</a>
					</p>
				</div>
			</div>
		</div>
		<div class="row mobile-wrap">
			<div class="col-md-5 col-md-push-7 animate-box">
				<%=image_tag("mobile-1.jpg",class:"mobile-img", alt: "")%>
			</div>
			<div class="col-md-7 col-md-pull-5 animate-box">
				<div class="desc">
					<h2>Finish template creation</h2>
					<div class="features">
						<span class="icon">
							<i class="icon-lightbulb"></i>
						</span>
						<div class="f-desc">
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
								a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
						</div>
					</div>
					<div class="features">
						<span class="icon">
							<i class="icon-circle-compass"></i>
						</span>
						<div class="f-desc">
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
								a small line of blind text by the name</p>
						</div>
					</div>
					<div class="features">
						<span class="icon">
							<i class="icon-beaker"></i>
						</span>
						<div class="f-desc">
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
								a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
						</div>
					</div>
					<p>
						<a href="#" class="btn btn-primary btn-outline with-arrow">Start collaborating
							<i class="icon-arrow-right3"></i>
						</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="colorlib-counter" class="colorlib-counters counter-back-image" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-4 col-sm-4 text-center animate-box">
					<div class="counter-entry">
						<span class="icon">
							<i class="flaticon-ribbon"></i>
						</span>
						<div class="desc">
							<span class="colorlib-counter js-counter" data-from="0" data-to="1500" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Of customers are satisfied with our professional support</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 text-center animate-box">
					<div class="counter-entry">
						<span class="icon">
							<i class="flaticon-church"></i>
						</span>
						<div class="desc">
							<span class="colorlib-counter js-counter" data-from="0" data-to="500" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Amazing preset options to be mixed and combined</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 text-center animate-box">
					<div class="counter-entry">
						<span class="icon">
							<i class="flaticon-dove"></i>
						</span>
						<div class="desc">
							<span class="colorlib-counter js-counter" data-from="0" data-to="1200" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Average response time on live chat support channel</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="colorlib-blog">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
				<h2>News from our Blog</h2>
				<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
					a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 animate-box">
				<article>
					<h2>Building the Mention Sales Application on Unapp</h2>
					<p class="admin">
						<span>May 12, 2018</span>
					</p>
					<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
					<p class="author-wrap">
						<%=image_tag("person1.jpg",class:"author-img", alt: "")%>
							<a href="#" class="author">by Dave Miller</a>
					</p>
				</article>
			</div>
			<div class="col-md-4 animate-box">
				<article>
					<h2>Building the Mention Sales Application on Unapp</h2>
					<p class="admin">
						<span>May 12, 2018</span>
					</p>
					<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
					<p class="author-wrap">
						<%=image_tag("person2.jpg",class:"author-img", alt: "")%>
							<a href="#" class="author">by Dave Miller</a>
					</p>
				</article>
			</div>
			<div class="col-md-4 animate-box">
				<article>
					<h2>Building the Mention Sales Application on Unapp</h2>
					<p class="admin">
						<span>May 12, 2018</span>
					</p>
					<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
					<p class="author-wrap">
						<%=image_tag("person3.jpg",class:"author-img", alt: "")%>
							<a href="#" class="author">by Dave Miller</a>
					</p>
				</article>
			</div>
		</div>
	</div>
</div>

<div id="colorlib-subscribe" class="colorlib-subscribe counter-back-image" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-center colorlib-heading animate-box">
				<h2>Already trusted by over 10,000 users</h2>
				<p>Subscribe to receive unapp tips from instructors right to your inbox.</p>
			</div>
		</div>
		<div class="row animate-box">
			<div class="col-md-6 col-md-offset-3">
				<div class="row">
					<div class="col-md-12">
						<form class="form-inline qbstp-header-subscribe">
							<div class="col-three-forth">
								<div class="form-group">
									<input type="text" class="form-control" id="email" placeholder="Enter your email">
								</div>
							</div>
							<div class="col-one-third">
								<div class="form-group">
									<button type="submit" class="btn btn-primary">Subscribe Now</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="colorlib-pricing">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
				<h2>Pricing</h2>
				<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however
					a small line of blind text by the name</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 text-center animate-box">
				<div class="pricing">
					<h2 class="pricing-heading">Starter</h2>
					<div class="price">
						<sup class="currency">$</sup>9
						<small>per month</small>
					</div>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					<p>
						<a href="#" class="btn btn-primary">Select Plan</a>
					</p>
				</div>
			</div>
			<div class="col-md-3 text-center animate-box">
				<div class="pricing">
					<h2 class="pricing-heading">Basic</h2>
					<div class="price">
						<sup class="currency">$</sup>27
						<small>per month</small>
					</div>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					<p>
						<a href="#" class="btn btn-primary">Select Plan</a>
					</p>
				</div>
			</div>
			<div class="col-md-3 text-center animate-box">
				<div class="pricing">
					<h2 class="pricing-heading">Pro</h2>
					<div class="price">
						<sup class="currency">$</sup>74
						<small>per month</small>
					</div>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					<p>
						<a href="#" class="btn btn-primary">Select Plan</a>
					</p>
				</div>
			</div>
			<div class="col-md-3 text-center animate-box">
				<div class="pricing">
					<h2 class="pricing-heading">Unlimited</h2>
					<div class="price">
						<sup class="currency">$</sup>140
						<small>per month</small>
					</div>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					<p>
						<a href="#" class="btn btn-primary">Select Plan</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

unapp/Unapp-Ror/app/views/layouts/_hero.html.erb
<% title ||= nil %>
<% body ||= nil %>
<% link_name ||= nil %>
<% link ||= nil %>

<section id="home" class="video-hero bg-main-1" data-section="home">
	<div class="overlay"></div>
	<a class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=vqqt5p0q-eU',containment:'#home', showControls:false, autoPlay:true, loop:true, mute:true, startAt:0, opacity:1, quality:'default'}"></a>
	<div class="display-t text-center">
		<div class="display-tc">
			<div class="container">
				<div class="col-md-12 col-md-offset-0">
					<div class="animate-box">
						<h2><%= link_to title, posts_path %></h2>
						<p><%= body %></p>
						<p>
              <%= link_to link_name, link %>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

unapp/Unapp-Ror/app/views/layouts/_navigation.html.erb
<div class="colorlib-loader"></div>

<div id="page">
	<nav class="colorlib-nav" role="navigation">
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-md-2">
						<div id="colorlib-logo">
							<%= link_to root_path do %>Unapp
								<% end %>
						</div>
					</div>
					<div class="col-md-10 text-right menu-1">
						<ul>
							<li class="active">
								<%= link_to "Home", pages_about_path %>
							</li>
							<li class="has-dropdown">
								<%= link_to "Work", pages_work_path %>
									<ul class="dropdown">
										<li>
											<%= link_to "Work Grid", pages_work_grid_path %>
										</li>
										<li>
											<%= link_to "Work Grid Without Text", pages_work_grid_without_text_path %>
										</li>
									</ul>
							</li>
							<li>
								<%= link_to "Services", pages_services_path %>
							</li>
							<li>
								<%= link_to "Blog", posts_path %>
							</li>
							<li>
								<%= link_to "About", pages_about_path %>
							</li>
							<li>
								<%= link_to "Contact", pages_contact_path %>
							</li>
							<li>
								<% if current_user %>
								<li style="color:red;">
									<%= link_to "sign out", destroy_user_session_path, :method => :delete %>
									<%= link_to "my post", myposts_posts_path %>
									<%= current_user.email %>
								</li>
								<%else%>
								<li>
									<%= link_to "sign in", new_user_session_path %>
								</li>
								<% end %>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</nav>

unapp/Unapp-Ror/app/views/posts/_form.html.erb
<% post ||= nil %>
<div class="container">
  <div class="col-mt-8 col-md-pull-4 animate-box">

    <%= form_for post do |f| %>
      <div class="row form-group">
        <div class="col-md-12">
          <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col-md-12">
          <%= f.text_field :body, class: "form-control", placeholder: "Body" %>
        </div>
      </div>
      <%= f.file_field :avatar %>
      <div class="form-group">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

unapp/Unapp-Ror/app/views/posts/_like-btn.html.erb
  <a href="#" class="dislike_btn glyphicon glyphicon-thumbs-down" id="dislike_btn_<%=post.id%>" data-id="<%=post.id%>" data-url="<%=delete_like_post_path(post, user_id: current_user.id)%>" style="<%=@liked ? '' : 'display:none;' %>"
    >unlike</a>
  <a href="#" class="like_btn glyphicon glyphicon-thumbs-up" id="like_btn_<%=post.id%>" data-id="<%=post.id%>" data-url="<%=add_like_post_path(post, user_id: current_user.id)%>" style="<%= @liked ? 'display:none;' : '' %>"
    >like</a>
  <%= post.likes.size %>

unapp/Unapp-Ror/app/views/posts/edit.html.erb
<%= render 'layouts/hero', title: @post.title, body: @post.created_at.strftime("%Y %M %d"), link_name: "Back", link: post_path(@post) %>
<%= render 'form', post: @post %>

unapp/Unapp-Ror/app/views/posts/index.html.erb
<%= render 'layouts/hero', title: "Jay's Blog", body: "Welcome To Jay's Blog", link_name: "New", link: new_post_path %>

<div class="colorlib-blog">
	<div class="container">
    <% @post.each_with_index do |post, index| %>
    <% if index % 3 == 0 %>
      <div class="row">
    <% end %>
			<div class="col-md-4 animate-box">
				<article>
					<h2>
						<%= link_to post.title, post_path(post) %>
					</h2>
					<p class="admin">
						<span><%= post.created_at.strftime("%M %d, %Y")%></span>
					</p>
					<p><%= post.body %></p>
					<p class="author-wrap">
						<%=image_tag("person1.jpg",class:"author-img", alt: "")%>
					<span style="margin-left:50px;"><%= post.user.email %></span>
					</p>
					<br>
					<%= link_to "edit", edit_post_path(post)%>
					<%= link_to "delete", post_path(post), data: {method: :delete} %>
					<% if current_user %>
						<div id="like_partial_<%=post.id%>">
								<% liked = post.likes.find_by(user_id: current_user.id).present?%>
								<%= render "posts/like-btn", liked: @liked, post: post %>
						</div>
				<% end %>
				<!-- <button type="button" name="button" class="glyphicon glyphicon-thumbs-up"></button> -->
			</article>
		</div>
	<% if index % 3 == 2 %>
		</div>
	<%end%>
	<%end%>
</div>
</div>

<script>
$(function(){
	$(".like_btn, .dislike_btn ").click(function () {
		console.log("old");
		let post_id = $(this).data("id");
		let redirect_path = $(this).data("url");
		$("#like_btn_"+post_id).toggle();
		$("#dislike_btn_"+post_id).toggle();
		$.get(redirect_path);
		let before_value = parseInt($("#like-count-"+post_id).text());
		return false;
	})
})
</script>

unapp/Unapp-Ror/app/views/posts/myposts.html.erb
<%= render 'layouts/hero', title: "Jay's Blog", body: "Welcome To Jay's Blog", link_name: "New", link: new_post_path %>

<div class="colorlib-blog">
  <div class="container">
    <% current_user.posts.each_with_index do |post, index| %>
      <% if index % 3 == 0 %>
        <div class="row">
        <% end %>
        <div class="col-md-4 animate-box">
          <article>
            <h2>
              <%= link_to post.title, post_path(post) %>
            </h2>
            <p class="admin">
              <span><%= post.created_at.strftime("%M %d, %Y")%></span>
            </p>
            <p><%= post.body %></p>
            <p class="author-wrap">
              <%=image_tag("person1.jpg",class:"author-img", alt: "")%>
              <span style="margin-left:50px;"><%= post.user.email %></span>

            </p>
            <br>
            <%= link_to "edit", edit_post_path(post)%>
            <%= link_to "delete", post_path(post), data: {method: :delete} %>
          </article>
        </div>
        <% if index % 3 == 2 %>
        </div>
      <%end%>
  <%end%>
</div>
</div>

unapp/Unapp-Ror/app/views/posts/new.html.erb
<%= render 'layouts/hero', title: "Jay's Blog", body: "Add a new Post", link_name: "Home", link: posts_path %>
<%= render 'form', post: @post %>

unapp/Unapp-Ror/app/views/posts/show.html.erb
<%= render 'layouts/hero', title: @post.title, body: @post.created_at.strftime("%Y %M %d"), link_name: "Edit", link: edit_post_path(@post) %>
<div class="container">
  <%=@post.created_at.strftime("%Y %M %d")%><br>
  <%=@post.title %><br>
  <%=@post.body %><br>

  <% if @post.likes.where({user_id: current_user.id}).present? %>
  <%= link_to "", delete_like_post_path(@post, user_id: current_user.id, show: "true"), class: "glyphicon glyphicon-thumbs-down" %>
  <% else %>
    <%= link_to "", add_like_post_path(@post, user_id: current_user.id, show: "true"), class: "glyphicon glyphicon-thumbs-up" %>
  <% end %>
  <%= @post.likes.count %>
  <%= image_tag @post.avatar, style: "width:100px; height: 100px"%>
  <%= link_to "delete", post_path(@post), data: {method: :delete} %>
</div>